---
title: "R Notebook"
author: "Paco"
date: '2022-08-02'
output: html_document
---


# igraph


In case you need to connect to Cytoscape.

```{r}
require(RCy3)
cytoscapePing()
openSession("C:/Users/Paco/Desktop/24arabidopsis.cys")
nodetab=getTableColumns(table="node")
edgetab=getTableColumns(table="edge")
ig2 <- createIgraphFromNetwork("STRING network")

exportNetwork(
  filename = "C:/Users/Paco/Desktop/arabidopsis24.sif",
  type = "SIF",
  network = NULL,
  base.url = NULL
)
```


```{r}
# dds is the deseq2 result object
dds %>% column_to_rownames(var="X") %>% 
  filter(abs(log2FoldChange)>1) %>%
  filter(padj<0.05) %>%
  arrange(padj)%>%
  head(500)->dds

# normalized are normalized counts result from deseq
normalized %>% column_to_rownames(var="X")->normalized

# join both files and build the matrix
mat<-merge(dds, normalized2, by=0)
 
# extract the columns that you need for the matrix
cbind(mat[,1], mat[,8:13])-> mat
  

library(igraph)
  
# Create a graph adjacency based on correlation distances between genes in  pairwise fashion.
g <- graph.adjacency(
  as.matrix(as.dist(cor(t(mat), method="pearson"))),
  mode="undirected",
  weighted=TRUE,
  diag=FALSE
)
```






```{r}
# Simplfy the adjacency object
g2 <- simplify(g)

# Colour negative correlation edges as blue
E(g2)[which(E(g2)$weight<0)]$color <- "darkblue"

# Colour positive correlation edges as red
E(g2)[which(E(g2)$weight>0)]$color <- "darkred"

# Convert edge weights to absolute values
E(g2)$weight <- abs(E(g2)$weight)

# Change arrow size
# For directed graphs only
#E(g)$arrow.size <- 1.0

# Remove edges below absolute Pearson correlation 0.8
g2 <- delete_edges(g2, E(g2)[which(E(g2)$weight<0.5)])

# Remove any vertices remaining that have no edges
g2 <- delete.vertices(g2, degree(g2)==0)

# Assign names to the graph vertices (optional)
V(g2)$name <- V(g2)$name

# Change shape of graph vertices
V(g2)$shape <- "sphere"

# Change colour of graph vertices
V(g2)$color <- "skyblue"

# Change colour of vertex frames
V(g2)$vertex.frame.color <- "white"

# Scale the size of the vertices to be proportional to the level of expression of each gene represented by each vertex
# Multiply scaled vales by a factor of 10
#scale01 <- function(x){(x-min(x))/(max(x)-min(x))}
#vSizes <- (scale01(apply(matbueno, 1, mean)) + 1.0) * 10

# Amplify or decrease the width of the edges
edgeweights <- E(g2)$weight * 2.0

# Convert the graph adjacency object into a minimum spanning tree based on Prim's algorithm
mst24<- mst(g2, algorithm="prim")

```


```{r}
# identify communities in the tree object based on 'edge betweenness'
mst.communities24 <- edge.betweenness.community(mst24)
mst.clustering24 <- make_clusters(mst24, membership=mst.communities24$membership)
V(mst24)$color <- mst.communities24$membership + 1

length(mst.communities24)
sizes(mst.communities24)



plot(
  mst.clustering24, mst24,
  layout=layout.fruchterman.reingold,
  edge.curved=TRUE,
  vertex.label=NA,
  vertex.size=vSizes,
  vertex.label.dist=-0.5,
  vertex.label.color="black",
  asp=FALSE,
  vertex.label.cex=0.6,
  edge.width=edgeweights,
  edge.arrow.mode=0)

plot(
  mst24,
  layout=layout.fruchterman.reingold,
  edge.curved=TRUE,
  vertex.label=NA,
  vertex.size=vSizes,
  vertex.label.dist=-0.5,
  vertex.label.color="black",
  asp=FALSE,
  vertex.label.cex=0.6,
  edge.width=edgeweights,
  edge.arrow.mode=0)
```



## Basic information about the network

Get the number of nodes, edges, and density of the network
```{r}
n=vcount(g2)
m=ecount(g2)
n
m

# network density
edge_density(mst24)
```



## Centrality measures

### Degree

```{r}
Degree <- degree(mst24)

```


### Eigenvector Centrality


```{r}
Eig <- evcent(mst24)$vector
```


### Closeness


```{r}
Closeness <- closeness(mst24)
```


### Betweenness

```{r}
Betweenness <- betweenness(mst24)

```



## Comparing centrality scores


```{r}
centralities <- cbind(Degree, Eig,  Closeness, Betweenness)

centralities<- round(cor(centralities), 2)
centralities
```


```{r}
V(mst72)$degree <- degree(mst24)                        # Degree centrality
V(mst72)$eig <- evcent(mst24)$vector                    # Eigenvector centrality
V(mst72)$closeness <- closeness(mst72)                  # Closeness centrality
V(mst72)$betweenness <- betweenness(mst72)              # Vertex betweenness centrality
```

```{r}
centrality24 <- data.frame(row.names   = V(mst72)$name,
                         degree      = V(mst72)$degree,
                         closeness   = V(mst72)$closeness,
                         betweenness = V(mst72)$betweenness,
                         eigenvector = V(mst72)$eig)

centrality24 <- centrality24[order(row.names(centrality24)),]

# Plot the centrality measures

plot1<-ggplot(centrality24, aes(x=degree), bindwith=1)  +
  geom_bar(color = "#000000", fill = "#0099F8") +
  
  labs(
    x = "Degree",
    y = "Count"
  ) +
  theme_classic()


plot2<-ggplot(centrality24, aes(x=betweenness))  +
  geom_histogram(color = "#000000", fill = "#0099F8") +
  
  labs(
    x = "Betweennees",
    y = "Count"
  ) +
  theme_classic()
```

```{r}
# Generate 1000 random graphs


gl1 <- vector('list',1000)
gl2 <- vector('list',1000)
gl3 <- vector('list',1000)
   

# mst
for(i in 1:1000){
  gl1[[i]] <-  rewire(mst24, each_edge(prob = 0.05))
}

for(i in 1:1000){
  gl2[[i]] <-  rewire(mst48, each_edge(prob = 0.05))
}

for(i in 1:1000){
  gl3[[i]] <-  rewire(mst72, each_edge(prob = 0.05))
}

# Calculate average path length of 1000 random graphs


gl.aplsC24<- unlist(lapply(gl1, mean_distance, directed = FALSE))
gl.aplsC48<- unlist(lapply(gl2, mean_distance, directed = FALSE))
gl.aplsC72<- unlist(lapply(gl3, mean_distance, directed = FALSE))

#Average diameter


gl.aplsC24<- unlist(lapply(gl1, diameter, directed = FALSE))
gl.aplsC48<- unlist(lapply(gl2, diameter, directed = FALSE))
gl.aplsC72<- unlist(lapply(gl3, diameter, directed = FALSE))


# Calculate average transivity of 1000 random graphs


gl.aplsC24<- unlist(lapply(gl1, transitivity))
gl.aplsC48<- unlist(lapply(gl2, transitivity))
gl.aplsC72<- unlist(lapply(gl3, transitivity))


# Density

gl.aplsC24<- unlist(lapply(gl1, edge_density))
gl.aplsC48<- unlist(lapply(gl2, edge_density))
gl.aplsC72<- unlist(lapply(gl3, edge_density))

```


## ANOVA

```{r}

df <- data.frame(id=c(1:1000),
                 T1=gl.aplsC24,
                 T2=gl.aplsC48,
                 T3=gl.aplsC72)

df <- df %>%
  gather(key = "time", value = "score", T1, T2,T3) %>%
  convert_as_factor(id,time)

df %>%
  group_by(time) %>%
  get_summary_stats(score, type = "mean_sd")

bxp <- ggboxplot(df, x = "time", y = "score", add = "point")
bxp
 
 
ggqqplot(df, "score", facet.by = "time")

res.aov <- anova_test(data = df, dv = score, wid = id, within = time)
get_anova_table(res.aov)

```

```{r}
# pairwise comparisons
pwc <- df %>%
  pairwise_t_test(
    score ~ time, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc
```

```{r}
# Visualization: box plots with p-values
pwc <- pwc %>% add_xy_position(x = "time")
bxp + 
  stat_pvalue_manual(pwc) +
  labs(
    subtitle = get_test_label(res.aov, detailed = TRUE),
    caption = get_pwc_label(pwc)
  )
```


